apiVersion: v1
kind: Service
metadata:
  name: springboot-crud-svc
  labels:
    app: springboot-k8s
spec:
  selector:
    app: springboot-k8s
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort