apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: dmFpc2huYXZp   # Base64 encoded "vaishnavi"
  MYSQL_USER: ZGV2dXNlcg==           # Base64 encoded "devuser"
  MYSQL_PASSWORD: ZGV2cGFzcw==       # Base64 encoded "devpass"